version: "3.4"

services:
  weaviate:
    image: semitechnologies/weaviate:1.29.4
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      GRPC_PORT: "50051"
      ENABLE_MODULES: "text2vec-openai"
      CLUSTER_HOSTNAME: "node1"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
